### ISSUE TITLE
there is some wrong with the train-net you provided

### ISSUE THREAD

**Issue by chengyao0929** [chuanqi305/MobileNet-SSD#2]
Hi，I used  MobileNetSSD_train.prototxt you provided to train the model,but when i used MobileNetSSD_deploy.prototxt to test the model,there is
some wrong with MobileNetSSD_deploy.prototxt, "Incompatible error "，so i fixed the wrong and test the model，but could not find any detections，so can you tell me how to train the model？the MobileNetSSD_train.prototxt and MobileNetSSD_deploy.prototxt you provided is right？
thank you very much！

**Comment by chuanqi305** [comment]
Because the batch_norm, scale layer can be merged to conv layer at test stage, so I merged it from  MobileNetSSD_train.caffemodel to  MobileNetSSD_deploy.caffemodel.
I just uploaded the merge_bn.py, you can generate your own caffemodel by this script.
If you want to train other dataset than PASCAL VOC, you should change the conv_xx_mbox_conf layer output num like this:
84 --> (class count) * 4
126-->(class count) * 6
And you should change the layer name if your training is start with MobileNetSSD_train.caffemodel, 
or with no change of layer name but converge slowly if start with MobileNet_nofc.caffemodel.
After several(about 100K) training iterator, your loss will be 0.6 ~ 1.5, check your data set if this is not reached.

**Comment by kaishijeng** [comment]
Does you have demo.py for testing MobileNetSSD_deploy.prototxt and your trained model?
Any idea about fps of test speed and how it compares yolov2?

Thanks,

**Comment by chuanqi305** [comment]
The caffe implement of MobileNet is slow because there is no optimization for  depth-wise convolution.
I have tested  it on my in-house Android CNN framework, it's much faster than yolov2, and also faster than tiny-yolo.

**Comment by Numeria-Jun** [comment]
Hello,I have also have problems with chenyao0929 which send error message "couldn't find any detections", and I follow your answer to use merge.py creating MobileNetSSD_deploy.caffemodel,but it still doesn't work. the layer output has also been revise . the MobileNetSSD_train.prototxt and MobileNetSSD_deploy.prototxt you provided is right？thank you.

**Comment by youngxiao** [comment]
@chuanqi305 Hello, I trained MobileNet-SSD and test it. Then I found that the bottleneck of the computational cost was conv1x1. It cost more time than depthwise conv. Could you give some suggestions for optimization?
