### ISSUE TITLE
processing time

### ISSUE THREAD

**Issue by xyoungli** [chuanqi305/MobileNet-SSD#8]
thank you very much for your work.
i have trained my own data and deployed the model (300x300) with visual studio 2013 on one GPU gtx 1070.
but the detection time was 35ms per image, the same with VGG-16 model.
what could be the problem?

**Comment by chuanqi305** [comment]
The depth-wise convolution is implemented by 'group' parameter, that's the bottleneck. I have implemented it myself, and the performance is better than tinyyolo. I will open the source later.

**Comment by lxy890123** [comment]
thank you very much, and i am looking forward to testing on the new source.

**Comment by firefox1031** [comment]
I am also looking forward to your implementation of depth-wise convolution,when will you paln to release that source? @chuanqi305

**Comment by birdwcp** [comment]
@chuanqi305  
I replace the convolution layer with depth-wise convolution layer and still have the same problem.   
the MobileNet-SSD model(512x512) cost 38ms(no cudnn) and the VGG-16 model cost 32ms(cudnn) per image on  the GTX1080.
what about your performance?

**Comment by abrams90** [comment]
@birdwcp do you implement depth-wise convolution layer by yourself, or find it somewhere else? I am also trying to figure out the GPU Time problem.Thanks!

**Comment by birdwcp** [comment]
@abrams90 
I use this  https://github.com/farmingyard/caffe-mobilenet
the MobileNet-SSD model(300x300) cost only 7ms(no cudnn)per image on the GTX1080

**Comment by abrams90** [comment]
@birdwcp Thank you very much,it's very helpfull!

**Comment by abrams90** [comment]
@chuanqi305  looking forward to your test time of forward caculation in gpu.what really bothering me is even with depth_wise conv layer replaced ,my gpu time in 1070 is just 2x faster than cpu time in i5,and still cost nearly 100ms.It's even slower than vgg16.Thanks!

**Comment by xizi** [comment]
You can solve the processing time problem from https://github.com/yonghenglh6/DepthwiseConvolution

**Comment by chl916185** [comment]
How do you implement this? Can you provide source code？
@birdwcp

**Comment by 0801130205** [comment]
why don't convolution depth wise use engine: CUDNN instead of engine: Caffe?  In the layers of conv1/dw and conv2/dw and so on in MobileNet-SSD/train.prototxt, setting engine: CAFFE that means the layers can't use gpu to speed up. So why not use engine: CUDNN? @ @chuanqi305

**Comment by 0801130205** [comment]
@chuanqi305 
why don't convolution depth wise use engine: CUDNN instead of engine: Caffe? In the layers of conv1/dw and conv2/dw and so on in MobileNet-SSD/train.prototxt, setting engine: CAFFE that means the layers can't use gpu to speed up. So why not use engine: CUDNN?

**Comment by adithya-p** [comment]
@chuanqi305 @birdwcp How do you modify the **MobileNet-SSD** network from 300x300 to 512x512?
